// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 2.1.3226.27803
//   <NameSpace>Umc.Core.Tools.VSGesture.Actions</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><CustomUsings></CustomUsings><CollectionBase></CollectionBase>
//  <auto-generated>
// ------------------------------------------------------------------------------
namespace Umc.Core.Tools.VSGesture.Actions {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/GestureActionList.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/GestureActionList.xsd", IsNullable=false)]
    public partial class GestureActionList {
        
        private List<GestureActionListGestureItem> gestureItemField;
        
        public GestureActionList() {
            if ((this.gestureItemField == null)) {
                this.gestureItemField = new List<GestureActionListGestureItem>();
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GestureItem")]
        public List<GestureActionListGestureItem> GestureItem {
            get {
                return this.gestureItemField;
            }
            set {
                this.gestureItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/GestureActionList.xsd")]
    public partial class GestureActionListGestureItem {
        
        private string nameField;
        
        private string captionField;
        
        private string valueField;
        
        private string argumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Caption {
            get {
                return this.captionField;
            }
            set {
                this.captionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Argument {
            get {
                return this.argumentField;
            }
            set {
                this.argumentField = value;
            }
        }
    }
}
